#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  basic:

services:
  ca.PO.com:
    image: hyperledger/fabric-ca:ppc64le-1.1.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.PO.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.retailer-org.PO.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/794e60fde28d8a9269b30dfed7ec0016cca8f8dd9e27d899cb91e83a14eb12fb_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/retailer-org.PO.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.PO.com
    networks:
      - basic

  orderer.PO.com:
    container_name: orderer.PO.com
    image: hyperledger/fabric-orderer:ppc64le-1.1.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./config/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/PO.com/orderers/orderer.PO.com/:/etc/hyperledger/msp/orderer
        - ./crypto-config/peerOrganizations/retailer-org.PO.com/peers/supplier1.retailer1-org.PO.com/:/etc/hyperledger/msp/peerRetailerOrg
    networks:
      - basic

  supplier1.retailer-org.PO.com:
    container_name: supplier1.retailer-org.PO.com
    extends:
      file: ./peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=supplier1.retailer-org.PO.com
      - CORE_PEER_ADDRESS=supplier1.retailer-org.PO.com:7051
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - ./crypto-config/peerOrganizations/retailer-org.PO.com/peers/supplier1.retailer-org.PO.com/msp:/etc/hyperledger/msp/peer
    depends_on:
      - orderer.PO.com
      - couchdb

  supplier2.retailer-org.PO.com:
    container_name: supplier2.retailer-org.PO.com
    extends:
      file: ./peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=supplier2.retailer-org.PO.com
      - CORE_PEER_ADDRESS=supplier2.retailer-org.PO.com:7051
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - ./crypto-config/peerOrganizations/retailer-org.PO.com/peers/supplier2.retailer-org.PO.com/msp:/etc/hyperledger/msp/peer
    depends_on:
      - orderer.PO.com
      - couchdb

  supplier3.retailer-org.PO.com:
    container_name: supplier3.retailer-org.PO.com
    extends:
      file: ./peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=supplier3.retailer-org.PO.com
      - CORE_PEER_ADDRESS=supplier3.retailer-org.PO.com:7051
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
        - ./crypto-config/peerOrganizations/retailer-org.PO.com/peers/supplier3.retailer-org.PO.com/msp:/etc/hyperledger/msp/peer
    depends_on:
      - orderer.PO.com
      - couchdb

  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - basic

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:ppc64le-1.1.0
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=supplier1.retailer-org.PO.com:7051
      - CORE_PEER_LOCALMSPID=RetailerOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/retailer-org.PO.com/users/Admin@retailer-org.PO.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./config:/etc/hyperledger/configtx/
        - .:/opt/gopath/src/github.com/hyperledger/fabric/peer/run/
    networks:
        - basic
    #depends_on:
    #  - orderer.example.com
    #  - peer0.org1.example.com
    #  - couchdb
